warn_str = """# ------------------------------------------
#
# THIS MAKE FILE GENERATED BY make_make.py
#
# ------------------------------------------
"""

main_make_filename = "makefile"
make_debug_filename = "debug.mk"
make_release_filename = "release.mk"
make_analyze_filename = "analyze.mk"

# ------------------------------------------------------------------------------

import main_make_make

main_make_file = open(main_make_filename, "w")
main_make_file.write(warn_str + main_make_make.main_make_str)

# ------------------------------------------------------------------------------

import files_make_make

make_debug_file = open(make_debug_filename, "w")
make_debug_file.write(warn_str + files_make_make.make_debug_str)

make_release_file = open(make_release_filename, "w")
make_release_file.write(warn_str + files_make_make.make_release_str)

make_analyze_file = open(make_analyze_filename, "w")
make_analyze_file.write(warn_str + files_make_make.make_analyze_str)
